version: '3'
services:
  webhook-callback-receiver:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: webhook-callback-receiver
      PRIVATE_KEY_PATH: /var/opt/resources/privateKey.pem
      ENVIRONMENT_APP: sandbox
      PROJECT_ID: 5240459093868544
      CRON_EXPRESSION_TO_SYNC: 0 30 3 * * ?
    volumes:
      - /var/opt/resources:/var/opt/resources
