version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: luan
      POSTGRES_PASSWORD: starkbank_luan
      POSTGRES_DB: starkbankdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  invoice-issuer:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_APPLICATION_NAME: invoice-issuer
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/starkbankdb
      SPRING_DATASOURCE_USERNAME: luan
      SPRING_DATASOURCE_PASSWORD: starkbank_luan
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      PRIVATE_KEY_PATH: /var/opt/resources/privateKey.pem
      ENVIRONMENT_APP: sandbox
      PROJECT_ID: 5599669673525248
      LIMIT_ISSUES_PER_ITERATION: 10
      CRON_EXPRESSION_INVOICE_ISSUE: 0 0 0/3 * * *

volumes:
  postgres-data:
